apiVersion: apps/v1
kind: Deployment
metadata:
  name: lecturebe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lecturebe
  template:
    metadata:
      labels:
        app: lecturebe
    spec:
      containers:
      - name: lecturebe
        image: clcum/lecturebe:v0.1
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 500m
            memory: "256Mi"
          requests:
            cpu: 200m
            memory: "128Mi"
        env:
        - name: SERVER_ADDR
          value: "lecturedb-client.default.svc.cluster.local"
        - name: SERVER_PORT
          value: "50051"
---
apiVersion: v1
kind: Service
metadata:
  name: lecturebe
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: lecturebe
  type: ClusterIP